const fileIconMap: Record<string, string> = {
  // Code
  ts: "typescript",
  tsx: "typescript-react",
  js: "javascript",
  jsx: "javascript-react",
  py: "python",
  rb: "ruby",
  rs: "rust",
  go: "go",
  java: "java",
  kt: "kotlin",
  scala: "scala",
  swift: "swift",
  php: "php",
  c: "c",
  cpp: "cpp",
  cs: "csharp",
  h: "header",
  hpp: "header",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  ps1: "powershell",
  sql: "database",
  graphql: "graphql",
  gql: "graphql",
   prisma: "prisma",
   dart: "dart",
  lua: "lua",
  r: "r",
  pl: "perl",
  pm: "perl",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  clj: "clojure",
  cljs: "clojure",
  hs: "haskell",
  ml: "ocaml",
  zig: "zig",
  // Config
  json: "json",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  xml: "xml",
  ini: "config",
  cfg: "config",
  conf: "config",
  env: "env",
  // Markup
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  sass: "scss",
  less: "less",
  md: "markdown",
  mdx: "markdown",
  rst: "restructuredtext",
  // Docs
  txt: "text",
  pdf: "pdf",
  doc: "word",
  docx: "word",
  xls: "excel",
  xlsx: "excel",
  ppt: "powerpoint",
  pptx: "powerpoint",
  csv: "csv",
  // Images
  png: "image",
  jpg: "image",
  jpeg: "image",
  gif: "image",
  svg: "image",
  webp: "image",
  ico: "image",
  bmp: "image",
  // Video
  mp4: "video",
  webm: "video",
  avi: "video",
  mov: "video",
  // Fonts
  woff: "font",
  woff2: "font",
  ttf: "font",
  otf: "font",
  eot: "font",
  // Archives
  zip: "archive",
  tar: "archive",
  gz: "archive",
  bz2: "archive",
  xz: "archive",
  rar: "archive",
  "7z": "archive",
  // Git
  gitignore: "git",
  gitattributes: "git",
  gitmodules: "git",
  // Lock files
  "lock": "lock",
  // Binaries
  exe: "binary",
  bin: "binary",
  dll: "binary",
  so: "binary",
  dylib: "binary",
  wasm: "wasm",
};

const fileNameMap: Record<string, string> = {
  "package.json": "npm",
  "package-lock.json": "npm",
  "yarn.lock": "yarn",
  "pnpm-lock.yaml": "pnpm",
  "Dockerfile": "docker",
  ".dockerignore": "docker",
  "docker-compose.yml": "docker",
  "docker-compose.yaml": "docker",
  "Makefile": "make",
  "Cargo.toml": "rust",
  "Cargo.lock": "rust",
  "go.mod": "go",
  "go.sum": "go",
  "Gemfile": "ruby",
  "Gemfile.lock": "ruby",
  "requirements.txt": "python",
  "setup.py": "python",
  "pyproject.toml": "python",
  "Pipfile": "python",
  "CMakeLists.txt": "cmake",
  "README.md": "readme",
  "LICENSE": "license",
  "LICENSE.md": "license",
  ".gitignore": "git",
  ".gitlab-ci.yml": "gitlab",
  ".github": "github",
  ".eslintrc": "eslint",
  ".eslintrc.json": "eslint",
  ".prettierrc": "prettier",
  "tsconfig.json": "typescript",
  "webpack.config.js": "webpack",
  "vite.config.ts": "vite",
  "vite.config.js": "vite",
  "next.config.js": "nextjs",
  "next.config.mjs": "nextjs",
  "nuxt.config.ts": "nuxt",
  "tailwind.config.js": "tailwind",
  "tailwind.config.ts": "tailwind",
  ".env": "env",
   ".env.example": "env",
 };

export function getFileIcon(filename: string): string {
  const nameMatch = fileNameMap[filename];
  if (nameMatch) return nameMatch;

  const ext = filename.includes(".") ? filename.split(".").pop()?.toLowerCase() || "" : "";
  if (ext && fileIconMap[ext]) return fileIconMap[ext];

  return "file";
}

export function getLanguageFromExtension(ext: string): string {
  const languageMap: Record<string, string> = {
    ts: "TypeScript",
    tsx: "TypeScript (React)",
    js: "JavaScript",
    jsx: "JavaScript (React)",
    py: "Python",
    rb: "Ruby",
    rs: "Rust",
    go: "Go",
    java: "Java",
    kt: "Kotlin",
    scala: "Scala",
    swift: "Swift",
    php: "PHP",
    c: "C",
    cpp: "C++",
    cs: "C#",
    sh: "Shell",
    bash: "Bash",
    sql: "SQL",
    html: "HTML",
    css: "CSS",
    scss: "SCSS",
    less: "Less",
    md: "Markdown",
    json: "JSON",
    yaml: "YAML",
    yml: "YAML",
    toml: "TOML",
    xml: "XML",
    dockerfile: "Dockerfile",
    graphql: "GraphQL",
    prisma: "Prisma",
    dart: "Dart",
    lua: "Lua",
    r: "R",
    pl: "Perl",
    ex: "Elixir",
    erl: "Erlang",
    hs: "Haskell",
    clj: "Clojure",
    zig: "Zig",
  };

  return languageMap[ext.toLowerCase()] || "";
}
